In [1]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Dataset_CitizenGrivences/BBMP_grievance_data_2025.csv")

In [3]:
df = df.rename(columns={
    'Category': 'department'
})

In [4]:
df = df[['Sub Category', 'department']]
df = df.rename(columns={'Sub Category': 'text'})

In [7]:
df.columns
df.head()

                       text                     department
0  Street Light Not Working                     Electrical
1  Street Light Not Working                     Electrical
2              Garbage dump  Solid Waste (Garbage) Related
3  Street Light Not Working                     Electrical
4              Garbage dump  Solid Waste (Garbage) Related

In [8]:
df

                               text                     department
0          Street Light Not Working                     Electrical
1          Street Light Not Working                     Electrical
2                      Garbage dump  Solid Waste (Garbage) Related
3          Street Light Not Working                     Electrical
4                      Garbage dump  Solid Waste (Garbage) Related
...                             ...                            ...
126969  Garbage vehicle not arrived  Solid Waste (Garbage) Related
126970     Street Light Not Working                     Electrical
126971        footpath encroachment         Road Maintenance(Engg)
126972     Street Light Not Working                     Electrical
126973                     Footpath         Road Maintenance(Engg)

[126974 rows x 2 columns]